//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetodosPontoFrequencia.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.163;Initial Catalog=BD_PONTO_WEB;Persist Security Info=True" +
            ";User ID=Pontoweb;Password=Pontow3b;Enlist=False;Pooling=True;Min Pool Size=5")]
        public string PontoFrequenciaConnectionStringdada {
            get {
                return ((string)(this["PontoFrequenciaConnectionStringdada"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.163;Initial Catalog=BD_PONTO_WEB;Persist Security Info=True" +
            ";User ID=Pontoweb;Password=Pontow3b;Enlist=False;Pooling=True;Min Pool Size=5")]
        public string PontoFrequenciaConnectionStringdayan2 {
            get {
                return ((string)(this["PontoFrequenciaConnectionStringdayan2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.163;Initial Catalog=BD_PONTO_WEB;Persist Security Info=True" +
            ";User ID=Pontoweb;Password=Pontow3b;Enlist=False;Pooling=True;Min Pool Size=5")]
        public string PontoFrequenciaConnectionStringdayan {
            get {
                return ((string)(this["PontoFrequenciaConnectionStringdayan"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.163;Initial Catalog=BD_PONTO_WEB;Persist Security Info=True" +
            ";User ID=Pontoweb;Password=Pontow3b;Enlist=False;Pooling=True;Min Pool Size=5")]
        public string PontoFrequenciaConnectionStringpontowebD2 {
            get {
                return ((string)(this["PontoFrequenciaConnectionStringpontowebD2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.163;Initial Catalog=BD_PONTO_WEB;Persist Security Info=True" +
            ";User ID=Pontoweb;Password=Pontow3b;Enlist=False;Pooling=True;Min Pool Size=5")]
        public string PontoFrequenciaConnectionStringdayan6 {
            get {
                return ((string)(this["PontoFrequenciaConnectionStringdayan6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.163;Initial Catalog=BD_PONTO_WEB;Persist Security Info=True" +
            ";User ID=Pontoweb;Password=Pontow3b;Enlist=False;Pooling=True;Min Pool Size=5")]
        public string PontoFrequenciaConnectionStringpontowebD10 {
            get {
                return ((string)(this["PontoFrequenciaConnectionStringpontowebD10"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.163;Initial Catalog=BD_PONTO_WEB;Persist Security Info=True" +
            ";User ID=Pontoweb;Password=Pontow3b;Enlist=False;Pooling=True;Min Pool Size=5")]
        public string PontoFrequenciaConnectionStringDayan3 {
            get {
                return ((string)(this["PontoFrequenciaConnectionStringDayan3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.163;Initial Catalog=BD_PONTO_WEB;Persist Security Info=True" +
            ";User ID=Pontoweb;Password=Pontow3b;Enlist=False;Pooling=True;Min Pool Size=5")]
        public string PontoFrequenciaConnectionStringpontowebD3 {
            get {
                return ((string)(this["PontoFrequenciaConnectionStringpontowebD3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.163;Initial Catalog=BD_PONTO_WEB;Persist Security Info=True" +
            ";User ID=Pontoweb;Password=Pontow3b;Enlist=False;Pooling=True;Min Pool Size=5")]
        public string PontoFrequenciaConnectionStringdayanh {
            get {
                return ((string)(this["PontoFrequenciaConnectionStringdayanh"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.163;Initial Catalog=BD_PONTO_WEB;Persist Security Info=True" +
            ";User ID=Pontoweb;Password=Pontow3b;Enlist=False;Pooling=True;Min Pool Size=5")]
        public string PontoFrequenciaConnectionStringDayan4 {
            get {
                return ((string)(this["PontoFrequenciaConnectionStringDayan4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.163;Initial Catalog=BD_PONTO_WEB;Persist Security Info=True" +
            ";User ID=Pontoweb;Password=Pontow3b;Enlist=False;Pooling=True;Min Pool Size=5")]
        public string PontoFrequenciaConnectionStringDayan7 {
            get {
                return ((string)(this["PontoFrequenciaConnectionStringDayan7"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.163;Initial Catalog=BD_PONTO_WEB;Persist Security Info=True" +
            ";User ID=Pontoweb;Password=Pontow3b;Enlist=False;Pooling=True;Min Pool Size=5")]
        public string PontoFrequenciaConnectionStringpontowebD {
            get {
                return ((string)(this["PontoFrequenciaConnectionStringpontowebD"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.163;Initial Catalog=BD_PONTO_WEB;Persist Security Info=True" +
            ";User ID=Pontoweb;Password=Pontow3b;Enlist=False;Pooling=True;Min Pool Size=5")]
        public string PontoFrequenciaPMCConnectionString {
            get {
                return ((string)(this["PontoFrequenciaPMCConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.163;Initial Catalog=BD_PONTO_WEB;Persist Security Info=True" +
            ";User ID=Pontoweb;Password=Pontow3b;Enlist=False;Pooling=True;Min Pool Size=5")]
        public string PontoDevConnectionString {
            get {
                return ((string)(this["PontoDevConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.163;Initial Catalog=BD_PONTO_WEB;Persist Security Info=True" +
            ";User ID=Pontoweb;Password=Pontow3b;Enlist=False;Pooling=True;Min Pool Size=5")]
        public string PontoFrequenciaConnectionStringDev {
            get {
                return ((string)(this["PontoFrequenciaConnectionStringDev"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.163;Initial Catalog=BD_PONTO_WEB;Persist Security Info=True" +
            ";User ID=Pontoweb;Password=Pontow3b;Enlist=False;Pooling=True;Min Pool Size=5")]
        public string PontoFrequenciaConnectionStringSAD2 {
            get {
                return ((string)(this["PontoFrequenciaConnectionStringSAD2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.163;Initial Catalog=BD_PONTO_WEB;Persist Security Info=True" +
            ";User ID=Pontoweb;Password=Pontow3b;Enlist=False;Pooling=True;Min Pool Size=5")]
        public string PontoFrequenciaConnectionStringSAD10 {
            get {
                return ((string)(this["PontoFrequenciaConnectionStringSAD10"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.163;Initial Catalog=BD_PONTO_WEB;Persist Security Info=True" +
            ";User ID=Pontoweb;Password=Pontow3b;Enlist=False;Pooling=True;Min Pool Size=5")]
        public string PontoFrequenciaConnectionStringSAD3 {
            get {
                return ((string)(this["PontoFrequenciaConnectionStringSAD3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.163;Initial Catalog=BD_PONTO_WEB;Persist Security Info=True" +
            ";User ID=Pontoweb;Password=Pontow3b;Enlist=False;Pooling=True;Min Pool Size=5")]
        public string PontoFrequenciaConnectionStringSAD {
            get {
                return ((string)(this["PontoFrequenciaConnectionStringSAD"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.163;Initial Catalog=BD_PONTO_WEB;User ID=Pontoweb;Password=" +
            "Pontow3b")]
        public string PontoFrequenciaPMCConnectionString1 {
            get {
                return ((string)(this["PontoFrequenciaPMCConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.10.100.244;Initial Catalog=BD_PONTO_WEB;Persist Security Info=True" +
            ";User ID=Pontoweb;Password=Pontow3b;Enlist=False;Pooling=True;Min Pool Size=5")]
        public string PontoBKPConnectionString {
            get {
                return ((string)(this["PontoBKPConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=201.38.172.142\\\\SQLMETATI16,1433;Initial Catalog=PontoFrequenciaPMC;P" +
            "ersist Security Info=True;User ID=sa;Password=MetaTi@2016;Enlist=False;Pooling=T" +
            "rue;Min Pool Size=5")]
        public string PontoFrequenciaConnectionString {
            get {
                return ((string)(this["PontoFrequenciaConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=201.38.172.142\\\\SQLMETATI16,1433;Initial Catalog=PontoFrequenciaPMC;P" +
            "ersist Security Info=True;User ID=sa;Password=MetaTi@2016;Enlist=False;Pooling=T" +
            "rue;Min Pool Size=5")]
        public string PontoFrequenciaNConnectionString {
            get {
                return ((string)(this["PontoFrequenciaNConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
        <?xml version=""1.0"" encoding=""utf-16""?>
        <SerializableConnectionString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
        <ConnectionString>Data Source=184.173.11.205;Initial Catalog=PontoBKP;User ID=dbponto;Password=dbponto123</ConnectionString>
        <ProviderName>System.Data.SqlClient</ProviderName>
        </SerializableConnectionString>
      ")]
        public string PontoBKPConnectionString1 {
            get {
                return ((string)(this["PontoBKPConnectionString1"]));
            }
        }
    }
}
